# tower
---
- hosts:  all
  become: true
  user:
    name: "{{item}}"
    state:  present
  loop:
    - one
    - two
    - three
    - four
    - five
    - six
    - seven
    - eight
    - nine
    - ten
