---
- name: creating users
  hosts:  all
  become: true
  tasks:
    - name: create multipule users
      user:
        name: "{{item}}"
        state:  present
      loop:
        - one
        - two
        - three
        - four
        - five
        - six
        - seven
        - nine
        - ten
        
